### ISSUE TITLE
Release v0.1.5

### ISSUE THREAD

**Issue by HighCommander4** [clangd/node-clangd#18]
There have been some fixes, such as https://github.com/clangd/node-clangd/commit/fd4795ca8be8d0eea953ed1e8b11e2bc98349991, since v0.1.4.

However, as far as I can tell, vscode-clangd doesn't actually pick up these fixes because its `package.json` [specifies](https://github.com/clangd/vscode-clangd/blob/687314dcfaa2ff982bd2aa448ec5db544c5dd77b/package.json#L49) v0.1.4.

**Comment by HighCommander4** [comment]
Done in https://github.com/clangd/node-clangd/pull/19

**Comment by HighCommander4** [comment]
> Done in #19

Well, I updated `package.json`.

I guess there is also an `npm publish` step which needs to be done by someone with permissions (@kadircet?)

**Comment by sam-mccall** [comment]
Thanks for working this out, and sorry we didn't have a better system for this.

@clangd/install 0.1.15 is now published, and I've set up automation so that bumping the version number now automatically publishes.
