### ISSUE TITLE
Error: Couldn'd parse clangd --version output: Ubuntu clangd version 11.0.0-2~ubuntu20.04.1

### ISSUE THREAD

**Issue by GopherJ** [clangd/node-clangd#6]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

While using coc-clangd with Linux Mint v20, I found it's impossible to update clangd's version from system package to github release. I'm wondering if it's possible to correctly handle this? Like:

- being able to parse this strange system package version: `Ubuntu clangd version 11.0.0-2~ubuntu20.04.1`
- check if latest github release's version is greater than `11.0.0-2`
- download new github release to `~/.config/coc/extensions/coc-clangd-data` and gives a warning that `clangd.serverPath` should be changed in `coc-settings.json` to be able to use it.

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from `:CocList output` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): `Ubuntu clangd version 11.0.0-2~ubuntu20.04.1`
clangd extension version (from `:CocInfo`): `latest`
Operating system: `Linuxt Mint v20`

**Comment by fannheyward** [comment]
cc @sam-mccall , do we need to parse os special clangd, like `Ubuntu clangd version 11.0.0-2~ubuntu20.04.1`?

**Comment by GopherJ** [comment]
or maybe it should be `clangd` side, but we still need to distinguish between os special clangd & normal github release for better management as we don't want to replace os clangd

**Comment by sam-mccall** [comment]
For being able to update... does the command `clangd.install` not work? I don't think it should care what your current system version is, just the autoupdate.

For parsing the version: we could strip any prefix before "clangd version " and any part of the version after ~, I suppose.

For whether auto-update actually applies: the latest stable version is 11.0.0, so isn't your system package up-to-date anyway?

**Comment by GopherJ** [comment]
@sam-mccall looks like clangd 11.0.0 comsumes much more memory than latest github release, so I'd like to try to see if things improve

**Comment by sam-mccall** [comment]
Sorry about the long delay here.
But the last comment doesn't answer my question, `clangd.install` should do the same thing as `clangd.update`, but without the version check. Does it work?

Taking the version vendor strings at face value isn't necessarily great, e.g. Apple ships clangd ~10 with a version string of "Apple clangd 12.0.0", who knows what they'll do in the future.

Maybe we should have a list of allowed prefixes or something...

**Comment by HighCommander4** [comment]
Debian also builds with `CLANG_VENDOR` (resulting in a `Debian` prefix in the version) as seen in https://github.com/clangd/vscode-clangd/issues/279.
